### ISSUE TITLE
The project needs some updatings

### ISSUE THREAD

**Issue by miguelangellus** [PortalNetZone/libpythonproV2#4]
### Hey there,

Having a look at your controllers seems to me that the tool `pyup` is flagged to update, and some care is required.

I wonder if I could give some contribution.

**Comment by marcosranes** [comment]
Hey guy,

If you feel able to fix it, do the following:

* Grab a fork from the project to your Github account
* Create a new `branch` with the number of this issue (e.g. 04)
* After making your improvements to the project please send us a `PR`.

So, hold on until your improvement proposal has been properly evaluated, and then we'll decide for accepting it or not.

Please let me know If there's anything else I can help you with.

**Comment by miguelangellus** [comment]
### Yes, that's right. Thank you @marcosranes

**Comment by marcosranes** [comment]
You're welcome @miguelangellus.

Thank you for advising and opening the issue:
- #4

**Comment by marcosranes** [comment]
Hey @miguelangellus, 
The problem has been solved, thanks for collaborating with this project.
If you need you can open a new issue. 
Cheers!
